### ISSUE TITLE
seed.sql formatting wasn't letting final 8 tests pass

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/SQL-bear-organizer-lab#33]
I had to change my `seed.sql` file from this:

``` sql
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES
(1,"Mr. Chocolate", 20, "M", "dark brown", "calm", 0),
(2,"Rowdy", 10, "M", "black", "intense", 1),
(3,"Tabitha", 6, "F", "dark brown", "Nice", 1),
(4,"Sargeant Brown", 19, "M", "Green", "Slimy", 0),
(5,"Melissa", 13, "F", "dark brown", "goofy", 1),
(6,"Grinch", 2, "M", "Black", "Grinchy", 1),
(7,"Wendy", 6, "F", "Blue", "naive", 1),
(8,null, 20, "M", "black", "aggressive", 0);
```

to this:

``` sql
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (1,"Mr. Chocolate", 20, "M", "dark brown", "calm", 0);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (2,"Rowdy", 10, "M", "black", "intense", 1);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (3,"Tabitha", 6, "F", "dark brown", "Nice", 1);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (4,"Sargeant Brown", 19, "M", "Green", "Slimy", 0);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (5,"Melissa", 13, "F", "dark brown", "goofy", 1);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (6,"Grinch", 2, "M", "Black", "Grinchy", 1);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (7,"Wendy", 6, "F", "Blue", "naive", 1);
INSERT INTO bears (id, name, age, gender, color, temperament, alive) VALUES (8,null, 20, "M", "black", "aggressive", 0);
```

before any of the tests in the "querying the bears table" section would pass. RSpec output below:

``` ruby
querying the bears table
  selects all of the female bears and returns their name and age (FAILED - 1)

Failures:

  1) querying the bears table selects all of the female bears and returns their name and age
     Failure/Error: @sql_runner.execute_data
     SQLite3::SQLException:
       near ",": syntax error
     # /Users/Hobbes/.rvm/gems/ruby-2.2.3/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
     # /Users/Hobbes/.rvm/gems/ruby-2.2.3/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `new'
     # /Users/Hobbes/.rvm/gems/ruby-2.2.3/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `prepare'
     # /Users/Hobbes/.rvm/gems/ruby-2.2.3/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:223:in `execute_batch'
     # ./spec/select_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.05087 seconds (files took 0.46124 seconds to load)
10 examples, 1 failure

Failed examples:

rspec ./spec/select_spec.rb:12 # querying the bears table selects all of the female bears and returns their name and age
```

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by jenmyers** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
